from django.core.exceptions import ValidationError
import re


def validate_date_time(self, date_time):
    pass